export const CHOOSE_RENT_CITY = 'CHOOSE_RENT_CITY'
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION'
export const CHOOSE_PICK_TIME = 'CHOOSE_PICK_TIME'
export const CHOOSE_BACK_TIME = 'CHOOSE_BACK_TIME'
export const CHOOSE_PICK_AREA = 'CHOOSE_PICK_AREA'
export const SEARCH = 'SEARCH'

